name-template: "playground v$NEXT_PATCH_VERSION"
tag-template: "playground@v$NEXT_PATCH_VERSION"
tag-prefix: "playground@"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  $CHANGES
include-paths:
  - "apps/playground/"
  - ".github/"
  - "packages/ui/"
