packages:
  - "apps/*"
  - "libs/*"
  - "packages/*"

catalog:
  "react": "^18.3.1"
  "react-dom": "^18.3.1"
  "@types/react": "^18.3.12"
  "@types/react-dom": "^18.3.1"
  "vite": "^6.0.1"
  "@vitejs/plugin-react": "^4.3.4"
  "typescript": "~5.6.2"
