name: playground release drafter
on:
  push:
    paths:
      - "apps/playground/**"
      - ".github/workflows/playground-*.yml"
      - "packages/ui/**"
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-draft.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
